import type { NextPage } from "next";
import { GetServerSideProps } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

interface SSRPageProps {
  name: string;
}

const SSR: NextPage<SSRPageProps> = ({ name }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Hello from SSR</h1>
        <div className={styles.description}>
          <p>To: {name}</p>
          <p>From: Serverless Cloud</p>
        </div>
        <br />
        <p>
          Use the <code className={styles.code}>name</code> query parameter to
          change the greeting!
        </p>
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  return {
    props: {
      name: context.query.name || "World",
    },
  };
};

export default SSR;
